import { BettingcardProps } from '../components/bets/card/Bettingcard'

export const BettingData: Array<BettingcardProps> = [
  {
    id: '1',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '2',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '3',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '4',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '5',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '6',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '7',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '8',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '9',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '10',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '11',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'Soccer',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
  id: '12',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '13',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '14',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '15',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '16',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '17',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '18',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '19',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '20',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Basketball',
  bettingLogo: '/images/svgs/sidebar/basketball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},

{
  id: '21',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '22',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '23',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '24',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '25',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '26',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '27',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'World Cup',
  bettingLogo: '/images/svgs/sidebar/world-cup.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '28',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '29',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '30',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '31',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '32',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '33',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '34',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '35',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '36',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '37',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '38',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Tennis',
  bettingLogo: '/images/svgs/sidebar/tennis-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '1',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'US Football',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '2',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'US Football',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '3',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'US Football',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '4',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'US Football',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '5',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'US Football',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '6',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '7',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '8',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '9',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '10',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '11',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
}, {
  id: '1',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '2',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '3',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Combat Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '4',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Motor Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '5',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Sampdoria',
  bettingType: 'Motor Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '6',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Motor Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '7',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Motor Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},
{
  id: '8',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Motor Sports',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '9',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Cryptos',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '10',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Cryptos',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: '10.03.22',
  bettingVolume: '171',
},
{
  id: '11',
  series: 'Serie A',
  team1: 'Atalanta',
  team2: 'Juventus',
  bettingType: 'Cryptos',
  bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
  bettingTime: '12:00',
  bettingDate: '08.03.22',
  bettingDeadline: 'expired',
  bettingVolume: '171',
},

]
